### ISSUE TITLE
Rewrite SDK to builder pattern

### ISSUE THREAD

**Issue by vikiival** [paraspell/sdk#2]
We we talking with @dudo50 that the best we can do to support multiple pallets and make it simplier for developers would be a Builder pattern

### Rationale:

```ts
import { Builder } as ‘@paraspell/sdk’

const call = Builder(api).from(‘bsx’).to(‘ksm’).teleportTokens(‘KSM’).addr('destinationAddr').sum(currencySum).asV3().build()
```

Seems much easier than than current import of pallets or so

**Comment by dudo50** [comment]
Issue closing as code implementing feature was successfuly merged.
