### ISSUE TITLE
Fix bug with polkadotXCM pallet

### ISSUE THREAD

**Issue by dudo50** [paraspell/sdk#9]
- Some nodes are unable to receive assets from Relay chain
- Some nodes are unable to transfer assets to Relay chain

Issues encountered:
- UnableToCalculateWeight
- Too expensive
- Unable to transfer due to barrier

Needs further research.

**Comment by vikiival** [comment]
Maybe be more descriptive?

**Comment by dudo50** [comment]
Essentially, what I discovered is, that many of the nodes that have polkadotXCM pallet are not yet XCM compatible with other networks or are only partially. This means, that call construction done by SDK is correct, but nodes are unable to process these messages) I am researching each node now (Both Kusama & Polkadot networks) and making sure everything is tested in the main net to make sure SDK functionality is 100% before release.

**Comment by dudo50** [comment]
Closing this issue, polkadotXCM is matter of further research and periodic checking if new nodes became compatible.

**Comment by vikiival** [comment]
> Closing this issue, polkadotXCM issue been resolved 


PR or code reference where it was resolved ?
